language: node_js
node_js:
  - "4.2"
  - "5.5"
services:
  - mongodb
cache:
  directories:
  - node_modules
git:
  depth: 5
before_script:
  - npm prune
script:
  - npm run lint
  - npm test
  - npm run build
after_script:
  - npm run report-coverage